### ISSUE TITLE
Connection monitor exception: Error in panel.py

### ISSUE THREAD

**Issue by lucidicious** [mag1024/bosch-alarm-mode2#16]
Hi @mag1024,
I recently updated the bosch-alarm-homeassistant integration on my RPi 4 HA instance. Now I'm getting cyclic connection drops with my Solution 3000 panel. This is what's coming up in the debugging log:
`Logger: root
Source: /usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py:255
First occurred: 4:35:41 AM (109 occurrences)
Last logged: 11:05:55 AM

Connection monitor exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 251, in _monitor_connection
    await self._monitor_connection_once()
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 281, in _monitor_connection_once
    await self._connect(load_selector)
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 214, in _connect
    await self.load(load_selector)
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 151, in load
    await self._load_history()
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 231, in _load_history
    if any(area.is_armed() for area in self.areas):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bosch_alarm_mode2/panel.py", line 231, in <genexpr>
    if any(area.is_armed() for area in self.areas):
           ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'is_armed'
`

**Comment by sanjay900** [comment]
ill have a look

**Comment by sanjay900** [comment]
Should be fixed now

**Comment by lucidicious** [comment]
Thanks @sanjay900. Awesome work with this and your previous integration. I had my own working a while back by containerising the Vera LUA implementation and adding MQTT. So much neater having the support from Bosch. Looking forward to trying the non-polled FW once it's available.

**Comment by sanjay900** [comment]
Yeah, i've been told that the release for that is very close, so that will be good fun once its out!
