### ISSUE TITLE
B9512G OverflowError: int too big to convert

### ISSUE THREAD

**Issue by jswent** [mag1024/bosch-alarm-mode2#43]
After successfully connecting with the home assistant integration, the connection status becomes disconnected and the information is not loaded in. The error that is thrown is below. 

```
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/panel.py", line 189, in connect
await self._connect(load_selector)
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/panel.py", line 296, in _connect
await self.load(load_selector)
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/panel.py", line 200, in load
await self._load_status()
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/panel.py", line 313, in _load_status
await self._load_entity_status(CMD.POINT_STATUS, self.points)
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/panel.py", line 668, in _load_entity_status
response = await self._connection.send_command(status_cmd, request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/bosch_alarm_mode2/connection.py", line 46, in send_command
request.extend((len(data) + 1).to_bytes(length_size, 'big'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: int too big to convert
```

**Comment by mag1024** [comment]
Thank you for reporting!
How many points does your alarm panel have configured?

**Comment by sanjay900** [comment]
wow those panels let you have up to 599 points!

**Comment by jswent** [comment]
Wow that was actually the problem. Yes, over 300 points!  Happy to help.

**Comment by jswent** [comment]
Thanks for the fix! Appreciate all the work!
